package com.cotato.squadus.domain.auth.enums;

public enum SchoolDomain {
    GACHON_UNIVERSITY("gachon.ac.kr", "가천대학교"),
    CATHOLIC_SANGJI_COLLEGE("csj.ac.kr", "가톨릭상지대학교"),
    GANGDONG_COLLEGE("gangdong.ac.kr", "강동대학교"),
    GANGNEUNG_YEONGDONG_COLLEGE("gyc.ac.kr", "강릉영동대학교"),
    KANGWON_TOURISM_COLLEGE("kt.ac.kr", "강원관광대학"),
    KANGWON_DO_COLLEGE("gw.ac.kr", "강원도립대학"),
    KOJE_COLLEGE("koje.ac.kr", "거제대학교"),
    KYUNGGI_COLLEGE_OF_SCIENCE_AND_TECHNOLOGY("gtec.ac.kr", "경기과학기술대학교"),
    GYEONGNAM_PROVINCIAL_GEOCHEON_COLLEGE("gc.ac.kr", "경남도립거창대학"),
    GYEONGNAM_PROVINCIAL_NAMHAE_COLLEGE("namhae.ac.kr", "경남도립남해대학"),
    GYEONGNAM_INFORMATION_UNIVERSITY("kit.ac.kr", "경남정보대학교"),
    KYUNGMIN_UNIVERSITY("kyungmin.ac.kr", "경민대학교"),
    KYUNGBOK_UNIVERSITY("kbu.ac.kr", "경복대학교"),
    GYEONGBUK_COLLEGE_OF_SCIENCE("kbsc.ac.kr", "경북과학대학교"),
    GYEONGBUK_PROVINCIAL_UNIVERSITY("gpc.ac.kr", "경북도립대학교"),
    GYEONGBUK_COLLEGE("kbc.ac.kr", "경북전문대학교"),
    GYEONGSAN_1_COLLEGE("gs.ac.kr", "경산1대학교"),
    KYUNGWON_COLLEGE("kwc.ac.kr", "경원전문대학"),
    KYUNG_IN_WOMENS_UNIVERSITY("kic.ac.kr", "경인여자대학교"),
    KEIMYUNG_COLLEGE_UNIVERSITY("kmcu.ac.kr", "계명문화대학교"),
    KAYWON_COLLEGE_OF_ARTS("kaywon.ac.kr", "계원예술대학교"),
    GOGURYEO_UNIVERSITY("kgrc.ac.kr", "고구려대학교"),
    KOREA_UNIVERSITY("korea.ac.kr", "고려대학교"),
    SKKU("skku.edu", "성균관대학교"),
    KWANGYANG_HEALTH_COLLEGE("kwangyang.ac.kr", "광양보건대학교"),
    GWANGJU_HEALTH_COLLEGE("ghu.ac.kr", "광주보건대학교"),
    GUMI_COLLEGE("gumi.ac.kr", "구미대학교"),
    SAOTC("saotc.ac.kr", "구세군사관학교"),
    KOOKJE_UNIVERSITY("kookje.ac.kr", "국제대학교"),
    KUNSAN_NURSING_COLLEGE("kcn.ac.kr", "군산간호대학교"),
    KUNJANG_COLLEGE("kunjang.ac.kr", "군장대학교"),
    CHRISTIAN_COLLEGE_OF_NURSING("ccn.ac.kr", "기독간호대학교"),
    KIMCHEON_COLLEGE("kcs.ac.kr", "김천과학대학"),
    GIMCHEON_COLLEGE("gimcheon.ac.kr", "김천대학"),
    KIMPO_COLLEGE("kimpo.ac.kr", "김포대학교"),
    GIMHAE_COLLEGE("gimhae.ac.kr", "김해대학교"),
    NH_COLLEGE("nonghyup.ac.kr", "농협대학교"),
    DAEKYUNG_COLLEGE("tk.ac.kr", "대경대학교"),
    DAEGU_TECHNICAL_COLLEGE("ttc.ac.kr", "대구공업대학교"),
    DAEGU_SCIENCE_COLLEGE("tsu.ac.kr", "대구과학대학교"),
    DAEGU_FUTURE_COLLEGE("dfc.ac.kr", "대구미래대학교"),
    DAEGU_HEALTH_COLLEGE("dhc.ac.kr", "대구보건대학교"),
    DAEDEOK_COLLEGE("ddu.ac.kr", "대덕대학교"),
    DAEDONG_COLLEGE("daedong.ac.kr", "대동대학교"),
    DAELIM_UNIVERSITY("daelim.ac.kr", "대림대학교"),
    DAEWON_UNIVERSITY("daewon.ac.kr", "대원대학교"),
    DAEJEON_HEALTH_COLLEGE("hit.ac.kr", "대전보건대학교"),
    DONGKANG_COLLEGE("dkc.ac.kr", "동강대학교"),
    DONGNAM_HEALTH_UNIVERSITY("dongnam.ac.kr", "동남보건대학교"),
    DONGMYUNG_COLLEGE("tu.ac.kr", "동명대학"),
    DONGPUSAN_COLLEGE("dpc.ac.kr", "동부산대학교"),
    DONGSEOUL_UNIVERSITY("dsc.ac.kr", "동서울대학교"),
    DONGAH_MEDIA_AND_ARTS_COLLEGE("dima.ac.kr", "동아방송예술대학교"),
    DONGAIN_UNIVERSITY("dongac.ac.kr", "동아인재대학교"),
    DONGYANG_MIRAE_UNIVERSITY("dongyang.ac.kr", "동양미래대학교"),
    DONGWOO_COLLEGE("duc.ac.kr", "동우대학"),
    DONGWON_COLLEGE_OF_SCIENCE_AND_TECHNOLOGY("dist.ac.kr", "동원과학기술대학교"),
    DONGWON_UNIVERSITY("tw.ac.kr", "동원대학교"),
    DONGUI_COLLEGE("dit.ac.kr", "동의과학대학교"),
    DONGJU_COLLEGE("dongju.ac.kr", "동주대학교"),
    DOOWON_TECHNICAL_COLLEGE("doowon.ac.kr", "두원공과대학교"),
    MASAN_UNIVERSITY("masan.ac.kr", "마산대학교"),
    MYONGJI_COLLEGE("mjc.ac.kr", "명지전문대학"),
    MOKPO_SCIENCE_COLLEGE("mokpo-c.ac.kr", "목포과학대학교"),
    MOONKYUNG_COLLEGE("mkc.ac.kr", "문경대학교"),
    BAEHWA_WOMENS_UNIVERSITY("baewha.ac.kr", "배화여자대학교"),
    BAEKSEOK_CULTURAL_UNIVERSITY("bscu.ac.kr", "백석문화대학교"),
    PAEKCHE_INSTITUTE_OF_THE_ARTS("paekche.ac.kr", "백제예술대학교"),
    BYEOKSEONG_COLLEGE("bs.ac.kr", "벽성대학"),
    BUSAN_KYUNGSANG_UNIVERSITY("bsks.ac.kr", "부산경상대학교"),
    BUSAN_COLLEGE_OF_SCIENCE_AND_TECHNOLOGY("bist.ac.kr", "부산과학기술대학교"),
    BUSAN_WOMENS_COLLEGE("bwc.ac.kr", "부산여자대학교"),
    BUSAN_UNIVERSITY_OF_ARTS("busanarts.ac.kr", "부산예술대학교"),
    BUCHEON_UNIVERSITY("bc.ac.kr", "부천대학교"),
    SAMYOOK_HEALTH_UNIVERSITY("shu.ac.kr", "삼육보건대학"),
    SAMYOOK_UNIVERSITY("syu.ac.kr", "삼육의명대학"),
    SANGJI_YEONGSEO_COLLEGE("sy.ac.kr", "상지영서대학교"),
    SEOUL_NATIONAL_UNIVERSITY("snu.ac.kr", "서울대학교"),
    SEORABOL_COLLEGE("sorabol.ac.kr", "서라벌대학교"),
    SEOYEONG_UNIVERSITY("seoyeong.ac.kr", "서영대학교"),
    SEOUL_HEALTH_COLLEGE("shjc.ac.kr", "서울보건대학"),
    SEOUL_WOMENS_COLLEGE_OF_NURSING("snjc.ac.kr", "서울여자간호대학교"),
    SEOUL_INSTITUTE_OF_THE_ARTS("seoularts.ac.kr", "서울예술대학교"),
    SEOIL_UNIVERSITY("seoil.ac.kr", "서일대학교"),
    SEOJEONG_COLLEGE("seojeong.ac.kr", "서정대학교"),
    SOHAE_COLLEGE("sohae.ac.kr", "서해대학"),
    SUNLIN_COLLEGE("sunlin.ac.kr", "선린대학교"),
    SUNGDUK_COLLEGE("sdc.ac.kr", "성덕대학교"),
    SUNGSIM_FOREIGN_LANGUAGE_UNIVERSITY("sungsim.ac.kr", "성심외국어대학"),
    SAEKYUNG_COLLEGE("saekyung.ac.kr", "세경대학교"),
    SONGGOK_COLLEGE("songgok.ac.kr", "송곡대학교"),
    SONGWON_COLLEGE("songwon.ac.kr", "송원대학"),
    SONGHO_COLLEGE("songho.ac.kr", "송호대학교"),
    SUSEONG_COLLEGE("sc.ac.kr", "수성대학교"),
    SUWON_SCIENCE_COLLEGE("ssc.ac.kr", "수원과학대학교"),
    SUWON_WOMENS_COLLEGE("swc.ac.kr", "수원여자대학교"),
    SUNCHEON_FIRST_COLLEGE("suncheon.ac.kr", "순천제일대학"),
    SUNG_UI_WOMENS_UNIVERSITY("sewc.ac.kr", "숭의여자대학교"),
    SHINGU_COLLEGE("shingu.ac.kr", "신구대학교"),
    SHINSUNG_UNIVERSITY("shinsung.ac.kr", "신성대학교"),
    SHINANSAN_UNIVERSITY("sau.ac.kr", "신안산대학교"),
    SHINHUNG_COLLEGE("shc.ac.kr", "신흥대학교"),
    AJOU_MOTOR_COLLEGE("motor.ac.kr", "아주자동차대학"),
    ANDONG_SCIENCE_COLLEGE("asc.ac.kr", "안동과학대학교"),
    ANSAN_COLLEGE("ansan.ac.kr", "안산대학교"),
    YEOJU_INSTITUTE_OF_TECHNOLOGY("yit.ac.kr", "여주대학교"),
    YEONSUNG_UNIVERSITY("yeonsung.ac.kr", "연성대학교"),
    YEONSEI_UNIVERSITY("yonsei.ac.kr", "연세대학교"),
    YOUNAM_ENGINEERING_COLLEGE("yc.ac.kr", "연암공과대학교"),
    YEONGNAM_FOREIGN_LANGUAGE_COLLEGE("yflc.ac.kr", "영남외국어대학"),
    YEONGNAM_ENGINEERING_COLLEGE("ync.ac.kr", "영남이공대학교"),
    YUDEOK_CYBER_UNIVERSITY("ycc.ac.kr", "영진사이버대학"),
    YEONGJIN_COLLEGE("yjc.ac.kr", "영진전문대학"),
    OSAN_UNIVERSITY("osan.ac.kr", "오산대학교"),
    YONGINSUNGDAM_UNIVERSITY("ysc.ac.kr", "용인송담대학교"),
    WOOSONG_COLLEGE("wst.ac.kr", "우송공업대학"),
    WOOSONG_INFORMATION_COLLEGE("wsi.ac.kr", "우송정보대학"),
    ULSAN_COLLEGE_OF_SCIENCE_AND_TECHNOLOGY("uc.ac.kr", "울산과학대학교"),
    UNJISEMU_COLLEGE("wat.ac.kr", "웅지세무대학"),
    WONKWANG_HEALTH_COLLEGE("wkhc.ac.kr", "원광보건대학교"),
    WONJU_COLLEGE("wonju.ac.kr", "원주대학"),
    YUHAN_UNIVERSITY("yuhan.ac.kr", "유한대학교"),
    INDUK_UNIVERSITY("induk.ac.kr", "인덕대학교"),
    INCHEON_JAEUNGEUNIVERSITY("jeiu.ac.kr", "인천재능대학교"),
    INCHEON_TECHNICAL_COLLEGE("icc.ac.kr", "인천전문대학"),
    INHA_TECHNICAL_COLLEGE("itc.ac.kr", "인하공업전문대학"),
    JANGAN_UNIVERSITY("jangan.ac.kr", "장안대학교"),
    REDCROSS_NURSING_COLLEGE("cau.ac.kr", "적십자간호대학"),
    JEONNAM_SCIENCE_COLLEGE("chunnam-c.ac.kr", "전남과학대학교"),
    JEONNAM_PROVINCIAL_COLLEGE("dorip.ac.kr", "전남도립대학교"),
    JEONBUK_COLLEGE_OF_SCIENCE("jbsc.ac.kr", "전북과학대학교"),
    JEONJU_GIZON_COLLEGE("jk.ac.kr", "전주기전대학"),
    JEONJU_VISION_COLLEGE("jvision.ac.kr", "전주비전대학교"),
    JEJU_COLLEGE_OF_TOURISM("ctc.ac.kr", "제주관광대학교"),
    JEJU_COLLEGE_OF_INDUSTRIAL_INFORMATION("jeju.ac.kr", "제주산업정보대학"),
    JEJU_HANLA_UNIVERSITY("chu.ac.kr", "제주한라대학교"),
    CHOSUN_NURSING_COLLEGE("cnc.ac.kr", "조선간호대학교"),
    CHOSUN_ENGINEERING_COLLEGE("cst.ac.kr", "조선이공대학교"),
    JINJU_HEALTH_COLLEGE("jhc.ac.kr", "진주보건대학교"),
    CHANGSHIN_UNIVERSITY("csc.ac.kr", "창신대학"),
    CHANGWON_MOONSEONG_UNIVERSITY("cmu.ac.kr", "창원문성대학"),
    CHEONAN_YEONAM_COLLEGE("yonam.ac.kr", "천안연암대학"),
    CHUNGKANG_COLLEGE_OF_CULTURAL_INDUSTRIES("chungkang.academy", "청강문화산업대학교"),
    CHEONGNAM_COLLEGE("scjc.ac.kr", "청암대학교"),
    CHUNHAE_HEALTH_UNIVERSITY("ch.ac.kr", "춘해보건대학교"),
    CHUNGCHEONGNAM_PROVINCIAL_CHEONGLYANG_UNIVERSITY("cyc.ac.kr", "충남도립청양대학"),
    CHUNGBUK_PROVINCIAL_UNIVERSITY("cpu.ac.kr", "충북도립대학"),
    CHUNGBUK_HEALTH_AND_SCIENCE_UNIVERSITY("chsu.ac.kr", "충북보건과학대학교"),
    CHUNGCHUNG_COLLEGE("ok.ac.kr", "충청대학교"),
    POHANG_UNIVERSITY("pohang.ac.kr", "포항대학교"),
    KOREA_GOLF_COLLEGE("kg.ac.kr", "한국골프대학"),
    KOREA_TOURISM_COLLEGE("ktc.ac.kr", "한국관광대학교"),
    KOREA_NONGSUSAN_UNIVERSITY("af.ac.kr", "한국농수산대학"),
    KOREA_WELFARE_UNIVERSITY("hanrw.ac.kr", "한국복지대학교"),
    KOREA_CYBER_WELFARE_UNIVERSITY("corea.ac.kr", "한국복지사이버대학"),
    KOREA_ELEVATOR_UNIVERSITY("klc.ac.kr", "한국승강기대학교"),
    KOREA_VIDEO_UNIVERSITY("pro.ac.kr", "한국영상대학교"),
    KOREA_INFORMATION_AND_COMMUNICATION_UNIVERSITY("icpc.ac.kr", "한국정보통신기능대학"),
    KOREA_RAILROAD_COLLEGE("krc.ac.kr", "한국철도대학"),
    KOREA_POLYTECHNIC_1_SEOUL_GANGSEO_CAMPUS("kopo.ac.kr", "한국폴리텍 I 대학 서울강서캠퍼스"),
    KOREA_POLYTECHNIC_1_SEOUL_JEONGSU_CAMPUS("kopo.ac.kr", "한국폴리텍 I 대학 서울정수캠퍼스"),
    KOREA_POLYTECHNIC_1_SEONGNAM_CAMPUS("kopo.ac.kr", "한국폴리텍 I 대학 성남캠퍼스"),
    KOREA_POLYTECHNIC_2_NAMINCHEON_CAMPUS("kopo.ac.kr", "한국폴리텍 II 대학 남인천캠퍼스"),
    KOREA_POLYTECHNIC_2_INCHEON_CAMPUS("kopo.ac.kr", "한국폴리텍 II 대학 인천캠퍼스"),
    KOREA_POLYTECHNIC_3_GANGNEUNG_CAMPUS("kopo.ac.kr", "한국폴리텍 III 대학 강릉캠퍼스"),
    KOREA_POLYTECHNIC_3_CHUNCHEON_CAMPUS("kopo.ac.kr", "한국폴리텍 III 대학 춘천캠퍼스"),
    KOREA_POLYTECHNIC_4_DAEJEON_CAMPUS("kopo.ac.kr", "한국폴리텍 IV 대학 대전캠퍼스"),
    KOREA_POLYTECHNIC_4_ASAN_CAMPUS("kopo.ac.kr", "한국폴리텍 IV 대학 아산캠퍼스"),
    KOREA_POLYTECHNIC_4_CHEONGJU_CAMPUS("kopo.ac.kr", "한국폴리텍 IV 대학 청주캠퍼스"),
    KOREA_POLYTECHNIC_4_HONGSEONG_CAMPUS("kopo.ac.kr", "한국폴리텍 IV 대학 홍성캠퍼스"),
    KOREA_POLYTECHNIC_5_GOCHANG_CAMPUS("kopo.ac.kr", "한국폴리텍 V 대학 고창캠퍼스"),
    KOREA_POLYTECHNIC_5_KIMJE_CAMPUS("kopo.ac.kr", "한국폴리텍 V 대학 김제캠퍼스"),
    KOREA_POLYTECHNIC_5_MOKPO_CAMPUS("kopo.ac.kr", "한국폴리텍 V 대학 목포캠퍼스"),
    KOREA_POLYTECHNIC_5_IKSAN_CAMPUS("kopo.ac.kr", "한국폴리텍 V 대학 익산캠퍼스"),
    KOREA_POLYTECHNIC_6_DAEGU_CAMPUS("kopo.ac.kr", "한국폴리텍 VI 대학 대구캠퍼스"),
    KOREA_POLYTECHNIC_7_BUSAN_CAMPUS("kopo.ac.kr", "한국폴리텍 VII 대학 부산캠퍼스"),
    KOREA_POLYTECHNIC_7_ULSAN_CAMPUS("kopo.ac.kr", "한국폴리텍 VII 대학 울산캠퍼스"),
    KOREA_POLYTECHNIC_7_CHANGWON_CAMPUS("kopo.ac.kr", "한국폴리텍 VII 대학 창원캠퍼스"),
    KOREA_POLYTECHNIC_6_GUMI_CAMPUS("kopo.ac.kr", "한국폴리텍VI대학 구미캠퍼스"),
    KOREA_POLYTECHNIC_5_GWANGJU_CAMPUS("kopo.ac.kr", "한국폴리텍V대학 광주캠퍼스"),
    KOREA_POLYTECHNIC_BIO_CAMPUS("kopo.ac.kr", "한국폴리텍대학 바이오캠퍼스"),
    KOREA_POLYTECHNIC_FASHION_CAMPUS("kopo.ac.kr", "한국폴리텍대학 섬유패션캠퍼스"),
    KOREA_POLYTECHNIC_ANSEONG_WOMENS_CAMPUS("kopo.ac.kr", "한국폴리텍대학 안성여자캠퍼스"),
    KOREA_POLYTECHNIC_AVIATION_CAMPUS("kopo.ac.kr", "한국폴리텍대학 항공캠퍼스"),
    HALLIM_SUNGSHIM_COLLEGE("hsc.ac.kr", "한림성심대학교"),
    HANYANG_WOMENS_UNIVERSITY("hywoman.ac.kr", "한양여자대학교"),
    HANYOUNG_COLLEGE("hanyeong.ac.kr", "한영대학"),
    HYEJEON_COLLEGE("hj.ac.kr", "혜전대학"),
    HYECHON_COLLEGE("hu.ac.kr", "혜천대학교"),
    KAYA_UNIVERSITY("kaya.ac.kr", "가야대학교"),
    CATHOLIC_KWANDONG_UNIVERSITY("cku.ac.kr", "가톨릭관동대학교"),
    KWANGSHIN_UNIVERSITY("kwangshin.ac.kr", "광신대학교"),
    KWANGWOON_UNIVERSITY("kw.ac.kr", "광운대학교"),
    GWANGJU_CATHOLIC_UNIVERSITY("kjcatholic.ac.kr", "광주가톨릭대학교"),
    GIST("gist.ac.kr", "광주과학기술원"),
    GWANGJU_NATIONAL_UNIVERSITY_OF_EDUCATION("gnue.ac.kr", "광주교육대학교"),
    GWANGJU_UNIVERSITY("gwangju.ac.kr", "광주대학교"),
    GWANGJU_WOMENS_UNIVERSITY("kwu.ac.kr", "광주여자대학교"),
    HONGIK_UNIVERSITY("g.hongik.ac.kr", "홍익대학교"),
    JOONANG_UNIVERSITY("cau.ac.kr", "중앙대학교"),
    CHUNGBUK_UNIVERSITY("chungbuk.ac.kr", "중앙대학교"),
    SEONGSHIN_WOMENS_UNIVERSITY("sungshin.ac.kr", "성신여자대학교");

    private final String domain;
    private final String universityName;

    SchoolDomain(String domain, String universityName) {
        this.domain = domain;
        this.universityName = universityName;
    }

    public String getDomain() {
        return domain;
    }

    public String getUniversityName() {
        return universityName;
    }

    public static String getUniversityByDomain(String domain) {
        for (SchoolDomain school : values()) {
            if (school.getDomain().equals(domain)) {
                return school.getUniversityName();
            }
        }
        return null; // 도메인이 없을 경우 null 반환
    }
}
